### ISSUE TITLE
unfound script filename causes large output

### ISSUE THREAD

**Issue by nerdoug** [theAgingApprentice/hexbotMQTTScriptCompiler-#7]
If you enter a script filename that's not found:

Please enter the script file name:
absent
ERROR. Attempted read of absent resulted in error System.IO.FileNotFoundException: Could not find file 'C:\Users\DougElliott\Documents\VisualStudioCode\C#\Projects\hexbotMQTTScriptCompiler-\absent'.
File name: 'C:\Users\DougElliott\Documents\VisualStudioCode\C#\Projects\hexbotMQTTScriptCompiler-\absent'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)  
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, 
FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at HexbotCompiler.scriptFile.getSrcContent() in C:\Users\DougElliott\Documents\VisualStudioCode\C#\Projects\hexbotMQTTScriptCompiler-\Program.cs:line 207.        
Please enter the script file name:

**Comment by theAgingApprentice** [comment]
There is logic we have that checks for a file exiting before trying to open it. I took this out as the code looked cleaner but I agree that this error is not great. Putting the check for file exiting logic back in will fix this issue.

**Comment by nerdoug** [comment]
current code doesn't generate the long series of messages. closing issue
